-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Roster exposing (..)

import I18Next exposing (Delims(..), Translations, tf, trf)


title : List Translations -> String
title translations =
    tf translations "roster.title"


playerName : List Translations -> String
playerName translations =
    tf translations "roster.playerName"


armyName : List Translations -> String
armyName translations =
    tf translations "roster.armyName"


armySize : List Translations -> String
armySize translations =
    tf translations "roster.armySize"


faction : List Translations -> String
faction translations =
    tf translations "roster.faction"


subFaction : List Translations -> String
subFaction translations =
    tf translations "roster.subFaction"


realmOfOrigin : List Translations -> String
realmOfOrigin translations =
    tf translations "roster.realmOfOrigin"


startingSize : List Translations -> String
startingSize translations =
    tf translations "roster.startingSize"


currentQuest : List Translations -> String
currentQuest translations =
    tf translations "roster.currentQuest"


questReward : List Translations -> String
questReward translations =
    tf translations "roster.questReward"


questProgress : List Translations -> String
questProgress translations =
    tf translations "roster.questProgress"


artefactsOfPower : List Translations -> String
artefactsOfPower translations =
    tf translations "roster.artefactsOfPower"


uniqueEnhancements : List Translations -> String
uniqueEnhancements translations =
    tf translations "roster.uniqueEnhancements"


spells : List Translations -> String
spells translations =
    tf translations "roster.spells"


prayers : List Translations -> String
prayers translations =
    tf translations "roster.prayers"


endlessSpellsInvocations : List Translations -> String
endlessSpellsInvocations translations =
    tf translations "roster.endlessSpellsInvocations"


battalions : List Translations -> String
battalions translations =
    tf translations "roster.battalions"


gloryPoints : List Translations -> String
gloryPoints translations =
    tf translations "roster.gloryPoints"
