-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Roster exposing (..)

import I18Next exposing (Delims(..), Translations, tf, trf)


playerName : List Translations -> String
playerName translations =
    tf translations "roster.playerName"


armyName : List Translations -> String
armyName translations =
    tf translations "roster.armyName"


armySize : List Translations -> String
armySize translations =
    tf translations "roster.armySize"


faction : List Translations -> String
faction translations =
    tf translations "roster.faction"


subFaction : List Translations -> String
subFaction translations =
    tf translations "roster.subFaction"


realmOfOrigin : List Translations -> String
realmOfOrigin translations =
    tf translations "roster.realmOfOrigin"


startingSize : List Translations -> String
startingSize translations =
    tf translations "roster.startingSize"
