-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Roster exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


playerName : Translations -> String
playerName translations =
    t translations "roster.playerName"


armyName : Translations -> String
armyName translations =
    t translations "roster.armyName"


armySize : Translations -> String
armySize translations =
    t translations "roster.armySize"


faction : Translations -> String
faction translations =
    t translations "roster.faction"


subFaction : Translations -> String
subFaction translations =
    t translations "roster.subFaction"


realmOfOrigin : Translations -> String
realmOfOrigin translations =
    t translations "roster.realmOfOrigin"


startingSize : Translations -> String
startingSize translations =
    t translations "roster.startingSize"
