-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Roster.Territories exposing (..)

import I18Next exposing (Delims(..), Translations, tf, trf)


strongholdTerritoryList : List Translations -> String
strongholdTerritoryList translations =
    tf translations "roster.territories.strongholdTerritoryList"


imposingStrongholdTerritoryList : List Translations -> String
imposingStrongholdTerritoryList translations =
    tf translations "roster.territories.imposingStrongholdTerritoryList"


mightyStrongholdTerritoryList : List Translations -> String
mightyStrongholdTerritoryList translations =
    tf translations "roster.territories.mightyStrongholdTerritoryList"


stronghold : List Translations -> String
stronghold translations =
    tf translations "roster.territories.stronghold"


territories : List Translations -> String
territories translations =
    tf translations "roster.territories.territories"


strongholdName : List Translations -> String
strongholdName translations =
    tf translations "roster.territories.strongholdName"


territoryType : List Translations -> String
territoryType translations =
    tf translations "roster.territories.territoryType"


territoryUpgraded : List Translations -> String
territoryUpgraded translations =
    tf translations "roster.territories.territoryUpgraded"
